nlc_constants.invTypeToSlot = {
    [""] = 0,
    ["INVTYPE_RANGEDRIGHT"] 		= 18,
    ["INVTYPE_SHIELD"] 				= 17,
    ["INVTYPE_RANGED"] 				= 0,
    ["INVTYPE_WEAPON"] 				= 16,
    ["INVTYPE_2HWEAPON"] 			= 16,
    ["INVTYPE_WRIST"]				= 9,
    ["INVTYPE_TRINKET"]				= 13,
    ["INVTYPE_ROBE"]				= 5,
    ["INVTYPE_CLOAK"]				= 15,
    ["INVTYPE_HEAD"]				= 1,
    ["INVTYPE_HOLDABLE"]			= 17,
    ["INVTYPE_CHEST"]				= 5,
    ["INVTYPE_NECK"]				= 2,
    ["INVTYPE_TABARD"]				= 19,
    ["INVTYPE_LEGS"]				= 7,
    ["INVTYPE_HAND"]				= 10,
    ["INVTYPE_WAIST"]				= 6,
    ["INVTYPE_FEET"]				= 8,
    ["INVTYPE_SHOULDER"]			= 3,
    ["INVTYPE_FINGER"]				= 11,
    ["INVTYPE_BAG"]					= 0,
    ["INVTYPE_AMMO"]				= 0,
    ["INVTYPE_BODY"]				= 4, -- Shirt
    ["INVTYPE_QUIVER"]				= 0,
    ["INVTYPE_RELIC"]				= 18,
    ["INVTYPE_THROWN"]				= 18,
    ["INVTYPE_WEAPONMAINHAND"] 		= 16,
    ["INVTYPE_WEAPONMAINHAND_PET"]	= 16,	-- "Main Attack"
    ["INVTYPE_WEAPONOFFHAND"]		= 17,
}

nlc_constants.slotNameToNumber = {
    ["head"] = 1,
    ["neck"] = 2,
    ["shoulder"] = 3,
    ["chest"] = 5,
    ["waist"] = 6,
    ["legs"] = 7,
    ["feet"] = 8,
    ["wrist"] = 9,
    ["hands"] = 10,
    ["ring1"] = 11,
    ["ring2"] = 12,
    ["trinket1"] = 13,
    ["trinket2"] = 14,
    ["back"] = 15,
    ["mainhand"] = 16,
    ["offhand"] = 17,
    ["wand"] = 18,
}

nlc_constants.usableItemsByClass = {
    ["WARRIOR"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Bows",
        "Crossbows",
        "Guns",
        "Thrown",
        "Plate",
        "Mail",
        "Leather",
        "Cloth",
        "Shields",
    },
    ["PALADIN"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Librams",
        "Plate",
        "Mail",
        "Leather",
        "Cloth",
        "Shields",
    },
    ["HUNTER"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "Polearms",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Bows",
        "Crossbows",
        "Guns",
        "Mail",
        "Leather",
        "Cloth",
    },
    ["ROGUE"] = {
        "One-Handed Axes",
        "One-Handed Swords",
        "One-Handed Maces",
        "Daggers",
        "Fist Weapons",
        "Bows",
        "Crossbows",
        "Guns",
        "Thrown",
        "Leather",
        "Cloth",
    },
    ["PRIEST"] = {
        "One-Handed Maces",
        "Staves",
        "Daggers",
        "Wands",
        "Cloth",
    },
    ["DEATHKNIGHT"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Plate",
        "Mail",
        "Leather",
        "Cloth",
    },
    ["SHAMAN"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Totems",
        "Mail",
        "Leather",
        "Cloth",
        "Shields",
    },
    ["MAGE"] = {
        "One-Handed Swords",
        "Staves",
        "Daggers",
        "Wands",
        "Cloth",
    },
    ["WARLOCK"] = {
        "One-Handed Swords",
        "Staves",
        "Daggers",
        "Wands",
        "Cloth",
    },
    ["MONK"] = {},
    ["DRUID"] = {
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Idols",
        "Leather",
        "Cloth",
    },
    ["DEMONHUNTER"] = {},
    ["ALL"] = {
        "Miscellaneous",
    },
}
