nlc_constants.invTypeToSlot = {
    [""] = 0,
    ["INVTYPE_RANGEDRIGHT"] 		= 18,
    ["INVTYPE_SHIELD"] 				= 17,
    ["INVTYPE_RANGED"] 				= 0,
    ["INVTYPE_WEAPON"] 				= 16,
    ["INVTYPE_2HWEAPON"] 			= 16,
    ["INVTYPE_WRIST"]				= 9,
    ["INVTYPE_TRINKET"]				= 13,
    ["INVTYPE_ROBE"]				= 5,
    ["INVTYPE_CLOAK"]				= 15,
    ["INVTYPE_HEAD"]				= 1,
    ["INVTYPE_HOLDABLE"]			= 17,
    ["INVTYPE_CHEST"]				= 5,
    ["INVTYPE_NECK"]				= 2,
    ["INVTYPE_TABARD"]				= 19,
    ["INVTYPE_LEGS"]				= 7,
    ["INVTYPE_HAND"]				= 10,
    ["INVTYPE_WAIST"]				= 6,
    ["INVTYPE_FEET"]				= 8,
    ["INVTYPE_SHOULDER"]			= 3,
    ["INVTYPE_FINGER"]				= 11,
    ["INVTYPE_BAG"]					= 0,
    ["INVTYPE_AMMO"]				= 0,
    ["INVTYPE_BODY"]				= 4, -- Shirt
    ["INVTYPE_QUIVER"]				= 0,
    ["INVTYPE_RELIC"]				= 18,
    ["INVTYPE_THROWN"]				= 18,
    ["INVTYPE_WEAPONMAINHAND"] 		= 16,
    ["INVTYPE_WEAPONMAINHAND_PET"]	= 16,	-- "Main Attack"
    ["INVTYPE_WEAPONOFFHAND"]		= 17,
}

nlc_constants.slotNameToNumber = {
    ["head"] = 1,
    ["neck"] = 2,
    ["shoulder"] = 3,
    ["chest"] = 5,
    ["waist"] = 6,
    ["legs"] = 7,
    ["feet"] = 8,
    ["wrist"] = 9,
    ["hands"] = 10,
    ["ring1"] = 11,
    ["ring2"] = 12,
    ["trinket1"] = 13,
    ["trinket2"] = 14,
    ["back"] = 15,
    ["mainhand"] = 16,
    ["offhand"] = 17,
    ["wand"] = 18,
}

nlc_constants.usableItemsByClass = {
    ["WARRIOR"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Bows",
        "Crossbows",
        "Guns",
        "Thrown",
        "Plate",
        "Mail",
        "Leather",
        "Cloth",
        "Shields",
    },
    ["PALADIN"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Librams",
        "Plate",
        "Mail",
        "Leather",
        "Cloth",
        "Shields",
    },
    ["HUNTER"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "Polearms",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Bows",
        "Crossbows",
        "Guns",
        "Mail",
        "Leather",
        "Cloth",
    },
    ["ROGUE"] = {
        "One-Handed Axes",
        "One-Handed Swords",
        "One-Handed Maces",
        "Daggers",
        "Fist Weapons",
        "Bows",
        "Crossbows",
        "Guns",
        "Thrown",
        "Leather",
        "Cloth",
    },
    ["PRIEST"] = {
        "One-Handed Maces",
        "Staves",
        "Daggers",
        "Wands",
        "Cloth",
    },
    ["DEATHKNIGHT"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Swords",
        "Two-Handed Swords",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Plate",
        "Mail",
        "Leather",
        "Cloth",
    },
    ["SHAMAN"] = {
        "One-Handed Axes",
        "Two-Handed Axes",
        "One-Handed Maces",
        "Two-Handed Maces",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Totems",
        "Mail",
        "Leather",
        "Cloth",
        "Shields",
    },
    ["MAGE"] = {
        "One-Handed Swords",
        "Staves",
        "Daggers",
        "Wands",
        "Cloth",
    },
    ["WARLOCK"] = {
        "One-Handed Swords",
        "Staves",
        "Daggers",
        "Wands",
        "Cloth",
    },
    ["MONK"] = {},
    ["DRUID"] = {
        "One-Handed Maces",
        "Two-Handed Maces",
        "Polearms",
        "Staves",
        "Daggers",
        "Fist Weapons",
        "Idols",
        "Leather",
        "Cloth",
    },
    ["DEMONHUNTER"] = {},
    ["ALL"] = {
        "Miscellaneous",
    },
}

-- Boss Items
nlc_constants.sscItemDict = {
    ["Hydross the Unstable"] = {
        30056,
        32516,
        30050,
        30055,
        30047,
        30054,
        30048,
        30053,
        30052,
        33055,
        30664,
        30629,
        30049,
        30051
    },
    ["The Lurker Below"] = {
        30064,
        30067,
        30062,
        30060,
        30066,
        30065,
        30057,
        30059,
        30061,
        33054,
        30665,
        30063,
        30058
    },
    ["Leotheras the Blind"] = {
        30092,
        30097,
        30091,
        30096,
        30627,
        30095,
        30239,
        30240,
        30241
    },
    ["Fathom-Lord Karatheress"] = {
        30100,
        30101,
        30099,
        30663,
        30626,
        30090,
        30245,
        30246,
        30247
    },
    ["Morogrim Tidewalker"] = {
        30098,
        30079,
        30075,
        30085,
        30068,
        30084,
        30081,
        30008,
        30083,
        33058,
        30720,
        30082,
        30080
    },
    ["Lady Vashj"] = {
        30107,
        30111,
        30106,
        30104,
        30102,
        30112,
        30109,
        30110,
        30621,
        30103,
        30108,
        30105,
        30242,
        30243,
        30244
    },
    ["Trash"] = {
        30027,
        30022,
        30620,
        30023,
        30021,
        30025,
        30322,
        30321,
        30280,
        30281,
        30304,
        30301,
        30303,
        30302,
        30324,
        30323,
        30228,
        30283,
        30308,
        30305,
        30307,
        30306,
        30183
    }
};

nlc_constants.filetst = "file test";
